package qstrader.execution_handler;

import qstrader.event.OrderEvent;

/**
 *  The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a PortfolioHandler
    and the set of Fill objects that actually occur in the market.

    The handlers can be used to subclass simulated brokerages
    or live brokerages, with identical interfaces. This allows
    strategies to be backtested in a very similar manner to the
    live trading engine.

    ExecutionHandler can link to an optional Compliance component
    for simple record-keeping, which will keep track of all executed
    orders.
 *  
 * @author Darkness
 * @date 2016年12月16日 下午2:34:50
 * @version V1.0
 */
public interface AbstractExecutionHandler {

	/**
	 * Takes an OrderEvent and executes it, producing a FillEvent that gets placed onto the events queue.
	 *  
	 * @param event Contains an Event object with order information. 
	 * @author Darkness
	 * @date 2016年12月16日 下午2:36:26
	 * @version V1.0
	 */
    void execute_order(OrderEvent event);
       
}